### ISSUE TITLE
Variable \"$value\" expected value of type \"UniqueEnum\" which cannot be used as an input type

### ISSUE THREAD

**Issue by dimatillck** [yaacovCR/graphql-executor#174]
Hi, I'm getting such an error if using a non-nullable arg of type Enum with a default value and corresponding nullable variable in case there is no nullable arg of the same type in the schema.

It looks like `_toExecutorSchema` adds the non-nullable version of the enum to the `inputTypes` Set and to the `typeTree`. Then `coerceVariableValues` tries to get a nullable version of the enum (because of nullable variable) from the `inputTypes` Set and from the `typeTree`. It cannot do that because there is the only non-nullable version of the enum.

**Comment by yaacovCR** [comment]
Ahah! Thanks!

I hadn't considered that variables could be more relaxed than the corresponding input arguments because of default values. This is most certainly a bug. Thanks for pointing it out and thanks for being the first person besides me to raise an issue and PR!

Welcome!

**Comment by dimatillck** [comment]
It's pleasure for me to be helpful in this project ❤️

**Comment by yaacovCR** [comment]
Fixed in #176, available in latest release.

Thanks @dimatillck !!!

**Comment by dimatillck** [comment]
This is great!! 🎉 Thank you @yaacovCR
